<!--
  Metro Overview ai2html Component
  Generated by ai2html v0.102.1 - 2025-09-17 01:24
-->

<script>
  export let assetsPath = '/';
  let width = null;
</script>

<!-- ai2html output -->
<div
  id="g-marmaray-box"
  bind:clientWidth={width}
  class="ai2html"
  style="max-width: 1000px; margin: 0 auto; min-height: 400px; border: 2px solid blue;"
>
  <!-- Debug: Component is loading -->
  <div
    style="background: lightblue; padding: 10px; margin: 10px 0; border: 1px solid blue;"
  >
    DEBUG: MetroOverview Component<br />
    Assets Path: {assetsPath}<br />
    Image URL: {assetsPath}/images/graphics/marmaray.png
  </div>
  <!-- Artboard: Marmaray -->
  <div
    id="g-marmaray-artboard"
    class="g-artboard"
    style="width: 100%;"
    data-aspect-ratio="0.773"
    data-min-width="0"
  >
    <div style="padding: 0 0 129.4118% 0"></div>
    <img
      id="g-marmaray-img"
      class="g-aiImg"
      alt="Marmaray graphic"
      src="{assetsPath}/images/graphics/marmaray.png"
      style="pointer-events: none;"
      draggable="false"
    />
    <div
      id="g-ai0-1"
      class="g-Layer_1 g-aiAbs g-aiPointText"
      style="top:21.9918%;margin-top:-32.2px;left:31.3564%;width:232px; pointer-events: none; user-select: none;"
    >
      <p class="g-pstyle0" style="pointer-events: none; user-select: none;">
        Marmaray
      </p>
    </div>
  </div>
</div>

<!-- svelte-ignore css-unused-selector -->
<style lang="scss">
  #g-marmaray-box,
  #g-marmaray-box .g-artboard {
    margin: 0 auto;
  }

  #g-marmaray-box p {
    margin: 0;
  }

  #g-marmaray-box .g-aiAbs {
    position: absolute;
  }

  #g-marmaray-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
  }

  #g-marmaray-box .g-aiSymbol {
    position: absolute;
    box-sizing: border-box;
  }

  #g-marmaray-box .g-aiPointText p {
    white-space: nowrap;
  }

  #g-marmaray-artboard {
    position: relative;
    overflow: hidden;
  }

  #g-marmaray-artboard p {
    font-weight: 500;
    line-height: 60px;
    height: auto;
    filter: alpha(opacity=100);
    -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
    opacity: 1;
    letter-spacing: 0em;
    font-size: 50px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }

  #g-marmaray-artboard .g-pstyle0 {
    height: 60px;
  }
</style>
