model = "gpt-5-codex"
model_reasoning_effort = "low"

[mcpServers.analytics-mcp]
type = "http"
url = "https://my-mcp-server.dry-paper-2b40.workers.dev/mcp"
headers = {}

[mcpServers.linear]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.linear.app/sse"]

[mcpServers.mcp-server-chart]
command = "npx"
args = ["-y", "@antv/mcp-server-chart"]

[mcpServers.context7]
url = "https://mcp.context7.com/mcp"
headers = { CONTEXT7_API_KEY = "ctx7sk-92123302-752b-48e9-a8fe-9da351715144" }

[mcpServers.chrome-devtools]
command = "pnpx"
args = ["chrome-devtools-mcp@latest"]

[mcpServers.TaskManager]
command = "npx"
args = ["-y", "@smithery/cli@latest", "run", "@kazuph/mcp-taskmanager", "--config", "{}"]

[mcpServers."Reddit Content Fetcher"]
type = "http"
url = "https://server.smithery.ai/@ruradium/mcp-reddit/mcp?api_key=32c7eb66-e46c-4eb4-835f-a871a082afef"
headers = {}

[projects."/Users/nihatavci/bluprint_graphics-kit"]
trust_level = "trusted"

[mcp_servers.linear]
command = "npx"
args = ["-y", "linear"]
