# Cloudflare Worker configuration for Scrolli RSS Feed
name = "scrolli-rss-feed"
main = "scrolli-rss-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "scrolli-rss-feed"

[env.staging]
name = "scrolli-rss-feed-staging"

# Worker settings
[build]
command = ""

# Cron trigger for automatic updates (optional)
[[triggers]]
crons = ["0 */6 * * *"]  # Run every 6 hours

# KV storage for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

