<!-- Generated by Story Compiler -->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { scroller } from '$utils/scroll';
  import {
    SEO,
    SiteHeader,
    SiteFooter,
    Theme,
    SiteHeadline,
    BodyText,
    EndNotes,
  } from '@reuters-graphics/graphics-components';
  import { assets } from '$app/paths';
  import { page } from '$app/state';
  import pkg from '$pkg';
  import TurkeyMapChart from '$lib/components/charts/TurkeyMapChart.svelte';
  import IstanbulMetroMap from '$lib/components/charts/IstanbulMetroMap.svelte';
  import TimeChart from '$lib/components/charts/TimeChart.svelte';
  import '@reuters-graphics/graphics-components/scss/main.scss';
  import '$lib/styles/global.scss';

  // Story data and state
  let currentStep = 0;
  let scrollerInstance: any;

  // Story metadata
  const storyData = {
    seoTitle: "Marmaray'da Son 5 Yılda 29 İntihar Vakası",
    seoDescription:
      '2021-2025 yılları arasında Marmaray hatlarında yaşanan intihar vakalarının analizi',
    shareTitle: "Marmaray'da Son 5 Yılda 29 İntihar Vakası",
    shareDescription:
      "İstanbul'un iki yakasını birbirine bağlayan Marmaray hattında son beş yılda yaşanan intihar vakalarının detaylı analizi",
    shareImgPath: 'images/reuters-graphics.jpg',
    shareImgAlt: 'Marmaray intihar vakaları analizi',
    hed: "Marmaray'da Son 5 Yılda 29 İntihar Vakası",
    section: 'Graphics',
    sectionUrl: 'https://www.reuters.com/graphics/',
    authors: ['ALİ SAFA KORKUT'],
    publishTime: '2025-08-24T17:47:00.000Z',
    updateTime: '',
    endNotes: [],
  };

  // Component state management
  let turkeymapchartState = {};

  // Initialize scroller
  onMount(() => {
    console.log('🚀 Component mounted, initializing scroller...');

    // Wait for DOM to be ready
    setTimeout(() => {
      const stepElements = document.querySelectorAll('.step');
      console.log('📍 Found step elements:', stepElements.length);

      if (stepElements.length === 0) {
        console.error('❌ No .step elements found!');
        return;
      }

      // Better scroll detection for smooth transitions
      let observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            if (entry.isIntersecting && entry.intersectionRatio > 0.3) {
              const stepIndex = Array.from(stepElements).indexOf(entry.target);
              console.log(
                '📍 Step visible:',
                stepIndex,
                'ratio:',
                entry.intersectionRatio
              );
              if (stepIndex !== currentStep) {
                currentStep = stepIndex;
                console.log(
                  '🎬 Step changed to:',
                  currentStep,
                  '- triggering smooth transition'
                );
                updateVisuals(stepIndex);
              }
            }
          });
        },
        {
          threshold: [0.1, 0.3, 0.5, 0.7],
          rootMargin: '-10% 0px -10% 0px',
        }
      );

      stepElements.forEach((step) => {
        observer.observe(step);
        console.log('👀 Observing step:', step);
      });

      scrollerInstance = { destroy: () => observer.disconnect() };
    }, 100);
  });

  onDestroy(() => {
    if (scrollerInstance) {
      scrollerInstance.destroy();
    }
  });

  // Visual state management
  function updateVisuals(stepIndex: number) {
    switch (stepIndex) {
      case 2:
        // Update state for step 2.2
        turkeymapchartState.zoom = {
          region: 'istanbul',
          coordinates: [28.9784, 41.0082],
          level: 8,
        };
        break;
    }
  }
</script>

<SEO
  baseUrl={import.meta.env.BASE_URL}
  pageUrl={page.url}
  seoTitle={storyData.seoTitle}
  seoDescription={storyData.seoDescription}
  shareTitle={storyData.shareTitle}
  shareDescription={storyData.shareDescription}
  shareImgPath={`${assets}/${storyData.shareImgPath}`}
  shareImgAlt={storyData.shareImgAlt}
  publishTime={pkg?.reuters?.graphic?.published}
  updateTime={pkg?.reuters?.graphic?.updated}
  authors={pkg?.reuters?.graphic?.authors}
/>

<Theme base="light">
  <SiteHeader />

  <!-- Fullscreen map with overlayed text -->
  <div class="fullscreen-scrollytelling">
    <!-- Fullscreen background visual -->
    <div class="fullscreen-visual">
      <!-- Debug info -->
      <div
        style="position: absolute; top: 10px; right: 10px; background: rgba(0,0,0,0.8); color: white; padding: 5px; z-index: 2000; font-size: 12px;"
      >
        Current Step: {currentStep}
        <br />
        <button
          on:click={() => {
            currentStep = 0;
            updateVisuals(0);
          }}
          style="margin: 1px; padding: 2px 4px; font-size: 9px;">0</button
        >
        <button
          on:click={() => {
            currentStep = 1;
            updateVisuals(1);
          }}
          style="margin: 1px; padding: 2px 4px; font-size: 9px;">1</button
        >
        <button
          on:click={() => {
            currentStep = 2;
            updateVisuals(2);
          }}
          style="margin: 1px; padding: 2px 4px; font-size: 9px;">2</button
        >
        <button
          on:click={() => {
            currentStep = 3;
            updateVisuals(3);
          }}
          style="margin: 1px; padding: 2px 4px; font-size: 9px;">3</button
        >
        <button
          on:click={() => {
            currentStep = 4;
            updateVisuals(4);
          }}
          style="margin: 1px; padding: 2px 4px; font-size: 9px;">4</button
        >
        <button
          on:click={() => {
            currentStep = 5;
            updateVisuals(5);
          }}
          style="margin: 1px; padding: 2px 4px; font-size: 9px;">5</button
        >
      </div>

      <!-- Single map that fills entire screen -->
      {#if currentStep === 0}
        <!-- Dark intro background -->
        <div class="intro-background">
          <div class="intro-content">
            <h1>Marmaray'da İntihar Vakaları</h1>
            <p>Son 5 yılda 29 vaka yaşandı</p>
          </div>
        </div>
      {:else if currentStep >= 1 && currentStep <= 2}
        <!-- FULLSCREEN Turkey map that smoothly transitions -->
        <TurkeyMapChart
          width={window?.innerWidth || 1920}
          height={window?.innerHeight || 1080}
          zoomToIstanbul={currentStep >= 2}
          showMetroLines={currentStep >= 2}
        />
      {:else if currentStep === 3}
        <!-- Fullscreen metro map -->
        <IstanbulMetroMap />
      {:else if currentStep === 4}
        <!-- Fullscreen time chart -->
        <TimeChart
          width={window?.innerWidth || 1920}
          height={window?.innerHeight || 1080}
        />
      {:else}
        <!-- Conclusion background -->
        <div class="conclusion-background">
          <div class="conclusion-content">
            <h2>Çözüm Önerileri</h2>
            <p>Platform kapıları ve teknolojik önlemler</p>
          </div>
        </div>
      {/if}
    </div>

    <!-- Overlayed text content with high z-index -->
    <div class="overlayed-text">
      <SiteHeadline
        hed={storyData.hed}
        section={storyData.section}
        sectionUrl={storyData.sectionUrl}
        authors={storyData.authors}
        publishTime={storyData.publishTime}
        updateTime={storyData.updateTime}
      />

      <section class="step step-0">
        <div class="text-block">
          <h2>Marmaray'da Son 5 Yılda 29 İntihar Vakası</h2>
          <BodyText
            text="İstanbul'un iki yakasını birbirine bağlayan Marmaray hattı, her gün milyonlarca yolcuyu taşıyor. Ancak aynı hat, son beş yılda başka bir yolculuğun da sessiz bir tanığı oldu: Ölüm yolculuklarının."
          />
          <div class="editor-note">
            <strong>Editör Notu:</strong> Bu makale intihar konusunu ele almakta
            ve yaşamlarına son vermiş kişilerle ilgili ayrıntılar içermektedir.
          </div>
        </div>
      </section>

      <section class="step step-1">
        <div class="text-block">
          <BodyText
            text="2021 ile 2025 yılları arasında Marmaray istasyonlarında, kayıtlara geçen en az 29 intihar ya da intihar girişimi yaşandı."
          />
        </div>
      </section>

      <section class="step step-2">
        <div class="text-block">
          <BodyText
            text="Yenikapı, Ayrılık Çeşmesi ve Bostancı, en fazla ölümün yaşandığı duraklar olurken, vakalar en çok haftanın başında ve sabah saatlerinde meydana geldi."
          />
        </div>
      </section>

      <section class="step step-3">
        <div class="text-block">
          <BodyText
            text="Metro istasyonlarında da durum farklı değil. 2016'dan beri çeşitli metro istasyonlarda 22 intihar girişimi yaşandı."
          />
        </div>
      </section>

      <section class="step step-4">
        <div class="text-block">
          <BodyText
            text="Bu vakalar sadece sayılar değil. Her birinin arkasında bir yaşam hikayesi, bir aile trajedisi var."
          />
        </div>
      </section>

      <section class="step step-5">
        <div class="text-block">
          <h2>Çözüm İçin Atılabilecek Adımlar</h2>
          <BodyText
            text="Platform kapıları, dünyada en etkili fiziksel çözüm olarak öne çıkıyor."
          />
        </div>
      </section>
    </div>
  </div>

  <SiteFooter />
</Theme>

<style lang="scss">
  .scrollytelling-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1rem;
    min-height: 100vh;

    &.two-column {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 2rem;
      width: 100%;
    }

    &.full-width {
      max-width: 100%;
      padding: 0;
    }

    &.centered {
      max-width: 800px;
      margin: 0 auto;
    }
  }

  .graphic-pane {
    position: sticky;
    top: 2rem;
    height: 80vh;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #f8f9fa;
    border-radius: 8px;
    overflow: hidden;
    border: 3px solid red; /* Debug border to make it visible */
  }

  .text-content {
    padding: 2rem 0;
  }

  .step {
    margin-bottom: 100vh;
    padding: 2rem;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);

    &.spacing-compact {
      margin-bottom: 50vh;
      padding: 1rem;
    }

    &.spacing-spacious {
      margin-bottom: 150vh;
      padding: 3rem;
    }
  }

  .placeholder,
  .intro-placeholder {
    text-align: center;
    color: #666;

    h3 {
      font-size: 2rem;
      margin-bottom: 1rem;
    }
  }

  blockquote {
    border-left: 4px solid #f16e23;
    padding-left: 1rem;
    margin: 1rem 0;
    font-style: italic;

    cite {
      display: block;
      margin-top: 0.5rem;
      font-size: 0.9rem;
      color: #666;

      &::before {
        content: '— ';
      }
    }
  }

  @media (max-width: 768px) {
    .scrollytelling-container.two-column {
      grid-template-columns: 1fr;
      gap: 1rem;
    }

    .graphic-pane {
      position: relative;
      height: 50vh;
      top: 0;
    }

    .step {
      margin-bottom: 50vh;
    }
  }
</style>
