name: Test SvelteKit build
permissions:
  contents: read
  issues: write
on:
  push:
    branches:
      - master
jobs:
  build-app:
    name: SvelteKit build
    runs-on: ubuntu-latest
    env:
      TESTING: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          cache: 'yarn'
      - run: yarn install
      - run: npx mocha
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/bluprint_issue.md
