name: Test Graphics Kit
permissions:
  contents: read
  issues: write
on:
  push:
    branches:
      - master
  pull_request_review:
    types: [submitted]
jobs:
  build-app:
    if: ${{ (github.event.review.state == 'APPROVED') || (github.ref_name == 'master') }}
    name: SvelteKit builds
    runs-on: ubuntu-latest
    env:
      TESTING: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Config git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Run tests
        run: npx mocha
      - name: Create issue on fail
        uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/COMMIT_ERROR_ISSUE_TEMPLATE.md
